//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.INV2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Выплат доход.
    /// </summary>
    // *** Start programmer edit section *** (ВыплатДоход CustomAttributes)

    // *** End programmer edit section *** (ВыплатДоход CustomAttributes)
    [AutoAltered()]
    [Caption("Выплат доход")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ВыплатДоходE", new string[] {
            "Дата as \'Дата\'",
            "Требования as \'Требования\'",
            "Номер as \'Номер\'",
            "УпрОБъек as \'Упр о бъек\'",
            "Сотрудн as \'Сотрудн\'",
            "Сотрудн.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "Сотрудн.ФИО"})]
    [MasterViewDefineAttribute("ВыплатДоходE", "УпрОБъек", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "")]
    [MasterViewDefineAttribute("ВыплатДоходE", "Сотрудн", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ВыплатДоходL", new string[] {
            "Дата as \'Дата\'",
            "Требования as \'Требования\'",
            "Номер as \'Номер\'",
            "Сотрудн.ФИО as \'ФИО\'"})]
    public class ВыплатДоход : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private string fТребования;
        
        private int fНомер;
        
        private IIS.INV2.УпрОБъек fУпрОБъек;
        
        private IIS.INV2.Сотрудн fСотрудн;
        
        // *** Start programmer edit section *** (ВыплатДоход CustomMembers)

        // *** End programmer edit section *** (ВыплатДоход CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ВыплатДоход.Дата CustomAttributes)

        // *** End programmer edit section *** (ВыплатДоход.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ВыплатДоход.Дата Get start)

                // *** End programmer edit section *** (ВыплатДоход.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ВыплатДоход.Дата Get end)

                // *** End programmer edit section *** (ВыплатДоход.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВыплатДоход.Дата Set start)

                // *** End programmer edit section *** (ВыплатДоход.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ВыплатДоход.Дата Set end)

                // *** End programmer edit section *** (ВыплатДоход.Дата Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (ВыплатДоход.Номер CustomAttributes)

        // *** End programmer edit section *** (ВыплатДоход.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (ВыплатДоход.Номер Get start)

                // *** End programmer edit section *** (ВыплатДоход.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (ВыплатДоход.Номер Get end)

                // *** End programmer edit section *** (ВыплатДоход.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВыплатДоход.Номер Set start)

                // *** End programmer edit section *** (ВыплатДоход.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (ВыплатДоход.Номер Set end)

                // *** End programmer edit section *** (ВыплатДоход.Номер Set end)
            }
        }
        
        /// <summary>
        /// Требования.
        /// </summary>
        // *** Start programmer edit section *** (ВыплатДоход.Требования CustomAttributes)

        // *** End programmer edit section *** (ВыплатДоход.Требования CustomAttributes)
        [StrLen(255)]
        public virtual string Требования
        {
            get
            {
                // *** Start programmer edit section *** (ВыплатДоход.Требования Get start)

                // *** End programmer edit section *** (ВыплатДоход.Требования Get start)
                string result = this.fТребования;
                // *** Start programmer edit section *** (ВыплатДоход.Требования Get end)

                // *** End programmer edit section *** (ВыплатДоход.Требования Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВыплатДоход.Требования Set start)

                // *** End programmer edit section *** (ВыплатДоход.Требования Set start)
                this.fТребования = value;
                // *** Start programmer edit section *** (ВыплатДоход.Требования Set end)

                // *** End programmer edit section *** (ВыплатДоход.Требования Set end)
            }
        }
        
        /// <summary>
        /// Выплат доход.
        /// </summary>
        // *** Start programmer edit section *** (ВыплатДоход.Сотрудн CustomAttributes)

        // *** End programmer edit section *** (ВыплатДоход.Сотрудн CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудн"})]
        [NotNull()]
        public virtual IIS.INV2.Сотрудн Сотрудн
        {
            get
            {
                // *** Start programmer edit section *** (ВыплатДоход.Сотрудн Get start)

                // *** End programmer edit section *** (ВыплатДоход.Сотрудн Get start)
                IIS.INV2.Сотрудн result = this.fСотрудн;
                // *** Start programmer edit section *** (ВыплатДоход.Сотрудн Get end)

                // *** End programmer edit section *** (ВыплатДоход.Сотрудн Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВыплатДоход.Сотрудн Set start)

                // *** End programmer edit section *** (ВыплатДоход.Сотрудн Set start)
                this.fСотрудн = value;
                // *** Start programmer edit section *** (ВыплатДоход.Сотрудн Set end)

                // *** End programmer edit section *** (ВыплатДоход.Сотрудн Set end)
            }
        }
        
        /// <summary>
        /// Выплат доход.
        /// </summary>
        // *** Start programmer edit section *** (ВыплатДоход.УпрОБъек CustomAttributes)

        // *** End programmer edit section *** (ВыплатДоход.УпрОБъек CustomAttributes)
        [PropertyStorage(new string[] {
                "УпрОБъек"})]
        [NotNull()]
        public virtual IIS.INV2.УпрОБъек УпрОБъек
        {
            get
            {
                // *** Start programmer edit section *** (ВыплатДоход.УпрОБъек Get start)

                // *** End programmer edit section *** (ВыплатДоход.УпрОБъек Get start)
                IIS.INV2.УпрОБъек result = this.fУпрОБъек;
                // *** Start programmer edit section *** (ВыплатДоход.УпрОБъек Get end)

                // *** End programmer edit section *** (ВыплатДоход.УпрОБъек Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВыплатДоход.УпрОБъек Set start)

                // *** End programmer edit section *** (ВыплатДоход.УпрОБъек Set start)
                this.fУпрОБъек = value;
                // *** Start programmer edit section *** (ВыплатДоход.УпрОБъек Set end)

                // *** End programmer edit section *** (ВыплатДоход.УпрОБъек Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ВыплатДоходE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВыплатДоходE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВыплатДоходE", typeof(IIS.INV2.ВыплатДоход));
                }
            }
            
            /// <summary>
            /// "ВыплатДоходL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВыплатДоходL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВыплатДоходL", typeof(IIS.INV2.ВыплатДоход));
                }
            }
        }
    }
}
