//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.INV2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Договр инв.
    /// </summary>
    // *** Start programmer edit section *** (ДоговрИнв CustomAttributes)

    // *** End programmer edit section *** (ДоговрИнв CustomAttributes)
    [AutoAltered()]
    [Caption("Договр инв")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДоговрИнвE", new string[] {
            "Требования as \'Требования\'",
            "Дата as \'Дата\'",
            "Номер as \'Номер\'",
            "ПредмДог as \'Предм дог\'",
            "Обяз as \'Обяз\'",
            "ПодписьК as \'Подпись К\'",
            "ПодписьО as \'Подпись О\'",
            "Сумма as \'Сумма\'",
            "УпрОБъек as \'Упр о бъек\'",
            "Организация as \'Организация\'",
            "Организация.Наим as \'Наим\'",
            "Клиен as \'Клиен\'",
            "Клиен.Наим as \'Наим\'"}, Hidden=new string[] {
            "Организация.Наим",
            "Клиен.Наим"})]
    [MasterViewDefineAttribute("ДоговрИнвE", "УпрОБъек", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "")]
    [MasterViewDefineAttribute("ДоговрИнвE", "Организация", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наим")]
    [MasterViewDefineAttribute("ДоговрИнвE", "Клиен", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наим")]
    [View("ДоговрИнвL", new string[] {
            "Требования as \'Требования\'",
            "Дата as \'Дата\'",
            "Номер as \'Номер\'",
            "ПредмДог as \'Предм дог\'",
            "Обяз as \'Обяз\'",
            "ПодписьК as \'Подпись К\'",
            "ПодписьО as \'Подпись О\'",
            "Сумма as \'Сумма\'",
            "Организация.Наим as \'Наим\'",
            "Клиен.Наим as \'Наим\'"})]
    public class ДоговрИнв : ICSSoft.STORMNET.DataObject
    {
        
        private string fТребования;
        
        private System.DateTime fДата;
        
        private int fНомер;
        
        private string fПредмДог;
        
        private string fОбяз;
        
        private bool fПодписьК;
        
        private bool fПодписьО;
        
        private float fСумма;
        
        private IIS.INV2.УпрОБъек fУпрОБъек;
        
        private IIS.INV2.Организация fОрганизация;
        
        private IIS.INV2.Клиен fКлиен;
        
        // *** Start programmer edit section *** (ДоговрИнв CustomMembers)

        // *** End programmer edit section *** (ДоговрИнв CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ДоговрИнв.Дата CustomAttributes)

        // *** End programmer edit section *** (ДоговрИнв.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ДоговрИнв.Дата Get start)

                // *** End programmer edit section *** (ДоговрИнв.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ДоговрИнв.Дата Get end)

                // *** End programmer edit section *** (ДоговрИнв.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДоговрИнв.Дата Set start)

                // *** End programmer edit section *** (ДоговрИнв.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ДоговрИнв.Дата Set end)

                // *** End programmer edit section *** (ДоговрИнв.Дата Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (ДоговрИнв.Номер CustomAttributes)

        // *** End programmer edit section *** (ДоговрИнв.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (ДоговрИнв.Номер Get start)

                // *** End programmer edit section *** (ДоговрИнв.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (ДоговрИнв.Номер Get end)

                // *** End programmer edit section *** (ДоговрИнв.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДоговрИнв.Номер Set start)

                // *** End programmer edit section *** (ДоговрИнв.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (ДоговрИнв.Номер Set end)

                // *** End programmer edit section *** (ДоговрИнв.Номер Set end)
            }
        }
        
        /// <summary>
        /// Обяз.
        /// </summary>
        // *** Start programmer edit section *** (ДоговрИнв.Обяз CustomAttributes)

        // *** End programmer edit section *** (ДоговрИнв.Обяз CustomAttributes)
        [StrLen(255)]
        public virtual string Обяз
        {
            get
            {
                // *** Start programmer edit section *** (ДоговрИнв.Обяз Get start)

                // *** End programmer edit section *** (ДоговрИнв.Обяз Get start)
                string result = this.fОбяз;
                // *** Start programmer edit section *** (ДоговрИнв.Обяз Get end)

                // *** End programmer edit section *** (ДоговрИнв.Обяз Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДоговрИнв.Обяз Set start)

                // *** End programmer edit section *** (ДоговрИнв.Обяз Set start)
                this.fОбяз = value;
                // *** Start programmer edit section *** (ДоговрИнв.Обяз Set end)

                // *** End programmer edit section *** (ДоговрИнв.Обяз Set end)
            }
        }
        
        /// <summary>
        /// ПодписьК.
        /// </summary>
        // *** Start programmer edit section *** (ДоговрИнв.ПодписьК CustomAttributes)

        // *** End programmer edit section *** (ДоговрИнв.ПодписьК CustomAttributes)
        public virtual bool ПодписьК
        {
            get
            {
                // *** Start programmer edit section *** (ДоговрИнв.ПодписьК Get start)

                // *** End programmer edit section *** (ДоговрИнв.ПодписьК Get start)
                bool result = this.fПодписьК;
                // *** Start programmer edit section *** (ДоговрИнв.ПодписьК Get end)

                // *** End programmer edit section *** (ДоговрИнв.ПодписьК Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДоговрИнв.ПодписьК Set start)

                // *** End programmer edit section *** (ДоговрИнв.ПодписьК Set start)
                this.fПодписьК = value;
                // *** Start programmer edit section *** (ДоговрИнв.ПодписьК Set end)

                // *** End programmer edit section *** (ДоговрИнв.ПодписьК Set end)
            }
        }
        
        /// <summary>
        /// ПодписьО.
        /// </summary>
        // *** Start programmer edit section *** (ДоговрИнв.ПодписьО CustomAttributes)

        // *** End programmer edit section *** (ДоговрИнв.ПодписьО CustomAttributes)
        public virtual bool ПодписьО
        {
            get
            {
                // *** Start programmer edit section *** (ДоговрИнв.ПодписьО Get start)

                // *** End programmer edit section *** (ДоговрИнв.ПодписьО Get start)
                bool result = this.fПодписьО;
                // *** Start programmer edit section *** (ДоговрИнв.ПодписьО Get end)

                // *** End programmer edit section *** (ДоговрИнв.ПодписьО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДоговрИнв.ПодписьО Set start)

                // *** End programmer edit section *** (ДоговрИнв.ПодписьО Set start)
                this.fПодписьО = value;
                // *** Start programmer edit section *** (ДоговрИнв.ПодписьО Set end)

                // *** End programmer edit section *** (ДоговрИнв.ПодписьО Set end)
            }
        }
        
        /// <summary>
        /// ПредмДог.
        /// </summary>
        // *** Start programmer edit section *** (ДоговрИнв.ПредмДог CustomAttributes)

        // *** End programmer edit section *** (ДоговрИнв.ПредмДог CustomAttributes)
        [StrLen(255)]
        public virtual string ПредмДог
        {
            get
            {
                // *** Start programmer edit section *** (ДоговрИнв.ПредмДог Get start)

                // *** End programmer edit section *** (ДоговрИнв.ПредмДог Get start)
                string result = this.fПредмДог;
                // *** Start programmer edit section *** (ДоговрИнв.ПредмДог Get end)

                // *** End programmer edit section *** (ДоговрИнв.ПредмДог Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДоговрИнв.ПредмДог Set start)

                // *** End programmer edit section *** (ДоговрИнв.ПредмДог Set start)
                this.fПредмДог = value;
                // *** Start programmer edit section *** (ДоговрИнв.ПредмДог Set end)

                // *** End programmer edit section *** (ДоговрИнв.ПредмДог Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (ДоговрИнв.Сумма CustomAttributes)

        // *** End programmer edit section *** (ДоговрИнв.Сумма CustomAttributes)
        public virtual float Сумма
        {
            get
            {
                // *** Start programmer edit section *** (ДоговрИнв.Сумма Get start)

                // *** End programmer edit section *** (ДоговрИнв.Сумма Get start)
                float result = this.fСумма;
                // *** Start programmer edit section *** (ДоговрИнв.Сумма Get end)

                // *** End programmer edit section *** (ДоговрИнв.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДоговрИнв.Сумма Set start)

                // *** End programmer edit section *** (ДоговрИнв.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (ДоговрИнв.Сумма Set end)

                // *** End programmer edit section *** (ДоговрИнв.Сумма Set end)
            }
        }
        
        /// <summary>
        /// Требования.
        /// </summary>
        // *** Start programmer edit section *** (ДоговрИнв.Требования CustomAttributes)

        // *** End programmer edit section *** (ДоговрИнв.Требования CustomAttributes)
        [StrLen(255)]
        public virtual string Требования
        {
            get
            {
                // *** Start programmer edit section *** (ДоговрИнв.Требования Get start)

                // *** End programmer edit section *** (ДоговрИнв.Требования Get start)
                string result = this.fТребования;
                // *** Start programmer edit section *** (ДоговрИнв.Требования Get end)

                // *** End programmer edit section *** (ДоговрИнв.Требования Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДоговрИнв.Требования Set start)

                // *** End programmer edit section *** (ДоговрИнв.Требования Set start)
                this.fТребования = value;
                // *** Start programmer edit section *** (ДоговрИнв.Требования Set end)

                // *** End programmer edit section *** (ДоговрИнв.Требования Set end)
            }
        }
        
        /// <summary>
        /// Договр инв.
        /// </summary>
        // *** Start programmer edit section *** (ДоговрИнв.Клиен CustomAttributes)

        // *** End programmer edit section *** (ДоговрИнв.Клиен CustomAttributes)
        [PropertyStorage(new string[] {
                "Клиен"})]
        [NotNull()]
        public virtual IIS.INV2.Клиен Клиен
        {
            get
            {
                // *** Start programmer edit section *** (ДоговрИнв.Клиен Get start)

                // *** End programmer edit section *** (ДоговрИнв.Клиен Get start)
                IIS.INV2.Клиен result = this.fКлиен;
                // *** Start programmer edit section *** (ДоговрИнв.Клиен Get end)

                // *** End programmer edit section *** (ДоговрИнв.Клиен Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДоговрИнв.Клиен Set start)

                // *** End programmer edit section *** (ДоговрИнв.Клиен Set start)
                this.fКлиен = value;
                // *** Start programmer edit section *** (ДоговрИнв.Клиен Set end)

                // *** End programmer edit section *** (ДоговрИнв.Клиен Set end)
            }
        }
        
        /// <summary>
        /// Договр инв.
        /// </summary>
        // *** Start programmer edit section *** (ДоговрИнв.Организация CustomAttributes)

        // *** End programmer edit section *** (ДоговрИнв.Организация CustomAttributes)
        [PropertyStorage(new string[] {
                "Организация"})]
        [NotNull()]
        public virtual IIS.INV2.Организация Организация
        {
            get
            {
                // *** Start programmer edit section *** (ДоговрИнв.Организация Get start)

                // *** End programmer edit section *** (ДоговрИнв.Организация Get start)
                IIS.INV2.Организация result = this.fОрганизация;
                // *** Start programmer edit section *** (ДоговрИнв.Организация Get end)

                // *** End programmer edit section *** (ДоговрИнв.Организация Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДоговрИнв.Организация Set start)

                // *** End programmer edit section *** (ДоговрИнв.Организация Set start)
                this.fОрганизация = value;
                // *** Start programmer edit section *** (ДоговрИнв.Организация Set end)

                // *** End programmer edit section *** (ДоговрИнв.Организация Set end)
            }
        }
        
        /// <summary>
        /// Договр инв.
        /// </summary>
        // *** Start programmer edit section *** (ДоговрИнв.УпрОБъек CustomAttributes)

        // *** End programmer edit section *** (ДоговрИнв.УпрОБъек CustomAttributes)
        [PropertyStorage(new string[] {
                "УпрОБъек"})]
        [NotNull()]
        public virtual IIS.INV2.УпрОБъек УпрОБъек
        {
            get
            {
                // *** Start programmer edit section *** (ДоговрИнв.УпрОБъек Get start)

                // *** End programmer edit section *** (ДоговрИнв.УпрОБъек Get start)
                IIS.INV2.УпрОБъек result = this.fУпрОБъек;
                // *** Start programmer edit section *** (ДоговрИнв.УпрОБъек Get end)

                // *** End programmer edit section *** (ДоговрИнв.УпрОБъек Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДоговрИнв.УпрОБъек Set start)

                // *** End programmer edit section *** (ДоговрИнв.УпрОБъек Set start)
                this.fУпрОБъек = value;
                // *** Start programmer edit section *** (ДоговрИнв.УпрОБъек Set end)

                // *** End programmer edit section *** (ДоговрИнв.УпрОБъек Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДоговрИнвE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДоговрИнвE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДоговрИнвE", typeof(IIS.INV2.ДоговрИнв));
                }
            }
            
            /// <summary>
            /// "ДоговрИнвL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДоговрИнвL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДоговрИнвL", typeof(IIS.INV2.ДоговрИнв));
                }
            }
        }
    }
}
