//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.INV2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Инв взн.
    /// </summary>
    // *** Start programmer edit section *** (ИнвВзн CustomAttributes)

    // *** End programmer edit section *** (ИнвВзн CustomAttributes)
    [AutoAltered()]
    [Caption("Инв взн")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ИнвВзнE", new string[] {
            "Дата as \'Дата\'",
            "Сумма as \'Сумма\'",
            "Подпись as \'Подпись\'",
            "Номер as \'Номер\'",
            "УпрОБъек as \'Упр о бъек\'",
            "ДоговрИнв as \'Договр инв\'",
            "ДоговрИнв.Требования as \'Требования\'"}, Hidden=new string[] {
            "ДоговрИнв.Требования"})]
    [MasterViewDefineAttribute("ИнвВзнE", "УпрОБъек", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "")]
    [MasterViewDefineAttribute("ИнвВзнE", "ДоговрИнв", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Требования")]
    [View("ИнвВзнL", new string[] {
            "Дата as \'Дата\'",
            "Сумма as \'Сумма\'",
            "Подпись as \'Подпись\'",
            "Номер as \'Номер\'",
            "ДоговрИнв.Требования as \'Требования\'",
            "ДоговрИнв.Организация.Наим"})]
    public class ИнвВзн : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private float fСумма;
        
        private bool fПодпись;
        
        private int fНомер;
        
        private IIS.INV2.УпрОБъек fУпрОБъек;
        
        private IIS.INV2.ДоговрИнв fДоговрИнв;
        
        // *** Start programmer edit section *** (ИнвВзн CustomMembers)

        // *** End programmer edit section *** (ИнвВзн CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ИнвВзн.Дата CustomAttributes)

        // *** End programmer edit section *** (ИнвВзн.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ИнвВзн.Дата Get start)

                // *** End programmer edit section *** (ИнвВзн.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ИнвВзн.Дата Get end)

                // *** End programmer edit section *** (ИнвВзн.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИнвВзн.Дата Set start)

                // *** End programmer edit section *** (ИнвВзн.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ИнвВзн.Дата Set end)

                // *** End programmer edit section *** (ИнвВзн.Дата Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (ИнвВзн.Номер CustomAttributes)

        // *** End programmer edit section *** (ИнвВзн.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (ИнвВзн.Номер Get start)

                // *** End programmer edit section *** (ИнвВзн.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (ИнвВзн.Номер Get end)

                // *** End programmer edit section *** (ИнвВзн.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИнвВзн.Номер Set start)

                // *** End programmer edit section *** (ИнвВзн.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (ИнвВзн.Номер Set end)

                // *** End programmer edit section *** (ИнвВзн.Номер Set end)
            }
        }
        
        /// <summary>
        /// Подпись.
        /// </summary>
        // *** Start programmer edit section *** (ИнвВзн.Подпись CustomAttributes)

        // *** End programmer edit section *** (ИнвВзн.Подпись CustomAttributes)
        public virtual bool Подпись
        {
            get
            {
                // *** Start programmer edit section *** (ИнвВзн.Подпись Get start)

                // *** End programmer edit section *** (ИнвВзн.Подпись Get start)
                bool result = this.fПодпись;
                // *** Start programmer edit section *** (ИнвВзн.Подпись Get end)

                // *** End programmer edit section *** (ИнвВзн.Подпись Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИнвВзн.Подпись Set start)

                // *** End programmer edit section *** (ИнвВзн.Подпись Set start)
                this.fПодпись = value;
                // *** Start programmer edit section *** (ИнвВзн.Подпись Set end)

                // *** End programmer edit section *** (ИнвВзн.Подпись Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (ИнвВзн.Сумма CustomAttributes)

        // *** End programmer edit section *** (ИнвВзн.Сумма CustomAttributes)
        public virtual float Сумма
        {
            get
            {
                // *** Start programmer edit section *** (ИнвВзн.Сумма Get start)

                // *** End programmer edit section *** (ИнвВзн.Сумма Get start)
                float result = this.fСумма;
                // *** Start programmer edit section *** (ИнвВзн.Сумма Get end)

                // *** End programmer edit section *** (ИнвВзн.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИнвВзн.Сумма Set start)

                // *** End programmer edit section *** (ИнвВзн.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (ИнвВзн.Сумма Set end)

                // *** End programmer edit section *** (ИнвВзн.Сумма Set end)
            }
        }
        
        /// <summary>
        /// Инв взн.
        /// </summary>
        // *** Start programmer edit section *** (ИнвВзн.ДоговрИнв CustomAttributes)

        // *** End programmer edit section *** (ИнвВзн.ДоговрИнв CustomAttributes)
        [PropertyStorage(new string[] {
                "ДоговрИнв"})]
        [NotNull()]
        public virtual IIS.INV2.ДоговрИнв ДоговрИнв
        {
            get
            {
                // *** Start programmer edit section *** (ИнвВзн.ДоговрИнв Get start)

                // *** End programmer edit section *** (ИнвВзн.ДоговрИнв Get start)
                IIS.INV2.ДоговрИнв result = this.fДоговрИнв;
                // *** Start programmer edit section *** (ИнвВзн.ДоговрИнв Get end)

                // *** End programmer edit section *** (ИнвВзн.ДоговрИнв Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИнвВзн.ДоговрИнв Set start)

                // *** End programmer edit section *** (ИнвВзн.ДоговрИнв Set start)
                this.fДоговрИнв = value;
                // *** Start programmer edit section *** (ИнвВзн.ДоговрИнв Set end)

                // *** End programmer edit section *** (ИнвВзн.ДоговрИнв Set end)
            }
        }
        
        /// <summary>
        /// Инв взн.
        /// </summary>
        // *** Start programmer edit section *** (ИнвВзн.УпрОБъек CustomAttributes)

        // *** End programmer edit section *** (ИнвВзн.УпрОБъек CustomAttributes)
        [PropertyStorage(new string[] {
                "УпрОБъек"})]
        [NotNull()]
        public virtual IIS.INV2.УпрОБъек УпрОБъек
        {
            get
            {
                // *** Start programmer edit section *** (ИнвВзн.УпрОБъек Get start)

                // *** End programmer edit section *** (ИнвВзн.УпрОБъек Get start)
                IIS.INV2.УпрОБъек result = this.fУпрОБъек;
                // *** Start programmer edit section *** (ИнвВзн.УпрОБъек Get end)

                // *** End programmer edit section *** (ИнвВзн.УпрОБъек Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИнвВзн.УпрОБъек Set start)

                // *** End programmer edit section *** (ИнвВзн.УпрОБъек Set start)
                this.fУпрОБъек = value;
                // *** Start programmer edit section *** (ИнвВзн.УпрОБъек Set end)

                // *** End programmer edit section *** (ИнвВзн.УпрОБъек Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ИнвВзнE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ИнвВзнE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ИнвВзнE", typeof(IIS.INV2.ИнвВзн));
                }
            }
            
            /// <summary>
            /// "ИнвВзнL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ИнвВзнL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ИнвВзнL", typeof(IIS.INV2.ИнвВзн));
                }
            }
        }
    }
}
