//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.INV2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Клиен.
    /// </summary>
    // *** Start programmer edit section *** (Клиен CustomAttributes)

    // *** End programmer edit section *** (Клиен CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КлиенE", new string[] {
            "Наим as \'Наим\'",
            "РасСчет as \'Рас счет\'",
            "БИК as \'БИК\'",
            "Банк as \'Банк\'",
            "ИНН as \'ИНН\'",
            "КПП as \'КПП\'"})]
    [View("КлиенL", new string[] {
            "Наим as \'Наим\'",
            "РасСчет as \'Рас счет\'",
            "БИК as \'БИК\'",
            "Банк as \'Банк\'",
            "ИНН as \'ИНН\'",
            "КПП as \'КПП\'"})]
    public class Клиен : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаим;
        
        private int fРасСчет;
        
        private int fБИК;
        
        private string fБанк;
        
        private int fИНН;
        
        private int fКПП;
        
        // *** Start programmer edit section *** (Клиен CustomMembers)

        // *** End programmer edit section *** (Клиен CustomMembers)

        
        /// <summary>
        /// Банк.
        /// </summary>
        // *** Start programmer edit section *** (Клиен.Банк CustomAttributes)

        // *** End programmer edit section *** (Клиен.Банк CustomAttributes)
        [StrLen(255)]
        public virtual string Банк
        {
            get
            {
                // *** Start programmer edit section *** (Клиен.Банк Get start)

                // *** End programmer edit section *** (Клиен.Банк Get start)
                string result = this.fБанк;
                // *** Start programmer edit section *** (Клиен.Банк Get end)

                // *** End programmer edit section *** (Клиен.Банк Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиен.Банк Set start)

                // *** End programmer edit section *** (Клиен.Банк Set start)
                this.fБанк = value;
                // *** Start programmer edit section *** (Клиен.Банк Set end)

                // *** End programmer edit section *** (Клиен.Банк Set end)
            }
        }
        
        /// <summary>
        /// БИК.
        /// </summary>
        // *** Start programmer edit section *** (Клиен.БИК CustomAttributes)

        // *** End programmer edit section *** (Клиен.БИК CustomAttributes)
        public virtual int БИК
        {
            get
            {
                // *** Start programmer edit section *** (Клиен.БИК Get start)

                // *** End programmer edit section *** (Клиен.БИК Get start)
                int result = this.fБИК;
                // *** Start programmer edit section *** (Клиен.БИК Get end)

                // *** End programmer edit section *** (Клиен.БИК Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиен.БИК Set start)

                // *** End programmer edit section *** (Клиен.БИК Set start)
                this.fБИК = value;
                // *** Start programmer edit section *** (Клиен.БИК Set end)

                // *** End programmer edit section *** (Клиен.БИК Set end)
            }
        }
        
        /// <summary>
        /// ИНН.
        /// </summary>
        // *** Start programmer edit section *** (Клиен.ИНН CustomAttributes)

        // *** End programmer edit section *** (Клиен.ИНН CustomAttributes)
        public virtual int ИНН
        {
            get
            {
                // *** Start programmer edit section *** (Клиен.ИНН Get start)

                // *** End programmer edit section *** (Клиен.ИНН Get start)
                int result = this.fИНН;
                // *** Start programmer edit section *** (Клиен.ИНН Get end)

                // *** End programmer edit section *** (Клиен.ИНН Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиен.ИНН Set start)

                // *** End programmer edit section *** (Клиен.ИНН Set start)
                this.fИНН = value;
                // *** Start programmer edit section *** (Клиен.ИНН Set end)

                // *** End programmer edit section *** (Клиен.ИНН Set end)
            }
        }
        
        /// <summary>
        /// КПП.
        /// </summary>
        // *** Start programmer edit section *** (Клиен.КПП CustomAttributes)

        // *** End programmer edit section *** (Клиен.КПП CustomAttributes)
        public virtual int КПП
        {
            get
            {
                // *** Start programmer edit section *** (Клиен.КПП Get start)

                // *** End programmer edit section *** (Клиен.КПП Get start)
                int result = this.fКПП;
                // *** Start programmer edit section *** (Клиен.КПП Get end)

                // *** End programmer edit section *** (Клиен.КПП Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиен.КПП Set start)

                // *** End programmer edit section *** (Клиен.КПП Set start)
                this.fКПП = value;
                // *** Start programmer edit section *** (Клиен.КПП Set end)

                // *** End programmer edit section *** (Клиен.КПП Set end)
            }
        }
        
        /// <summary>
        /// Наим.
        /// </summary>
        // *** Start programmer edit section *** (Клиен.Наим CustomAttributes)

        // *** End programmer edit section *** (Клиен.Наим CustomAttributes)
        [StrLen(255)]
        public virtual string Наим
        {
            get
            {
                // *** Start programmer edit section *** (Клиен.Наим Get start)

                // *** End programmer edit section *** (Клиен.Наим Get start)
                string result = this.fНаим;
                // *** Start programmer edit section *** (Клиен.Наим Get end)

                // *** End programmer edit section *** (Клиен.Наим Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиен.Наим Set start)

                // *** End programmer edit section *** (Клиен.Наим Set start)
                this.fНаим = value;
                // *** Start programmer edit section *** (Клиен.Наим Set end)

                // *** End programmer edit section *** (Клиен.Наим Set end)
            }
        }
        
        /// <summary>
        /// РасСчет.
        /// </summary>
        // *** Start programmer edit section *** (Клиен.РасСчет CustomAttributes)

        // *** End programmer edit section *** (Клиен.РасСчет CustomAttributes)
        public virtual int РасСчет
        {
            get
            {
                // *** Start programmer edit section *** (Клиен.РасСчет Get start)

                // *** End programmer edit section *** (Клиен.РасСчет Get start)
                int result = this.fРасСчет;
                // *** Start programmer edit section *** (Клиен.РасСчет Get end)

                // *** End programmer edit section *** (Клиен.РасСчет Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиен.РасСчет Set start)

                // *** End programmer edit section *** (Клиен.РасСчет Set start)
                this.fРасСчет = value;
                // *** Start programmer edit section *** (Клиен.РасСчет Set end)

                // *** End programmer edit section *** (Клиен.РасСчет Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КлиенE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиенE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиенE", typeof(IIS.INV2.Клиен));
                }
            }
            
            /// <summary>
            /// "КлиенL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиенL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиенL", typeof(IIS.INV2.Клиен));
                }
            }
        }
    }
}
