//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.INV2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Организация.
    /// </summary>
    // *** Start programmer edit section *** (Организация CustomAttributes)

    // *** End programmer edit section *** (Организация CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОрганизацияE", new string[] {
            "Наим as \'Наим\'",
            "РасСчет as \'Рас счет\'",
            "БИК as \'БИК\'",
            "Банк as \'Банк\'",
            "ИНН as \'ИНН\'",
            "КПП as \'КПП\'"})]
    [View("ОрганизацияL", new string[] {
            "Наим as \'Наим\'",
            "РасСчет as \'Рас счет\'",
            "БИК as \'БИК\'",
            "Банк as \'Банк\'",
            "ИНН as \'ИНН\'",
            "КПП as \'КПП\'"})]
    public class Организация : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаим;
        
        private int fРасСчет;
        
        private int fБИК;
        
        private string fБанк;
        
        private int fИНН;
        
        private int fКПП;
        
        // *** Start programmer edit section *** (Организация CustomMembers)

        // *** End programmer edit section *** (Организация CustomMembers)

        
        /// <summary>
        /// Банк.
        /// </summary>
        // *** Start programmer edit section *** (Организация.Банк CustomAttributes)

        // *** End programmer edit section *** (Организация.Банк CustomAttributes)
        [StrLen(255)]
        public virtual string Банк
        {
            get
            {
                // *** Start programmer edit section *** (Организация.Банк Get start)

                // *** End programmer edit section *** (Организация.Банк Get start)
                string result = this.fБанк;
                // *** Start programmer edit section *** (Организация.Банк Get end)

                // *** End programmer edit section *** (Организация.Банк Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организация.Банк Set start)

                // *** End programmer edit section *** (Организация.Банк Set start)
                this.fБанк = value;
                // *** Start programmer edit section *** (Организация.Банк Set end)

                // *** End programmer edit section *** (Организация.Банк Set end)
            }
        }
        
        /// <summary>
        /// БИК.
        /// </summary>
        // *** Start programmer edit section *** (Организация.БИК CustomAttributes)

        // *** End programmer edit section *** (Организация.БИК CustomAttributes)
        public virtual int БИК
        {
            get
            {
                // *** Start programmer edit section *** (Организация.БИК Get start)

                // *** End programmer edit section *** (Организация.БИК Get start)
                int result = this.fБИК;
                // *** Start programmer edit section *** (Организация.БИК Get end)

                // *** End programmer edit section *** (Организация.БИК Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организация.БИК Set start)

                // *** End programmer edit section *** (Организация.БИК Set start)
                this.fБИК = value;
                // *** Start programmer edit section *** (Организация.БИК Set end)

                // *** End programmer edit section *** (Организация.БИК Set end)
            }
        }
        
        /// <summary>
        /// ИНН.
        /// </summary>
        // *** Start programmer edit section *** (Организация.ИНН CustomAttributes)

        // *** End programmer edit section *** (Организация.ИНН CustomAttributes)
        public virtual int ИНН
        {
            get
            {
                // *** Start programmer edit section *** (Организация.ИНН Get start)

                // *** End programmer edit section *** (Организация.ИНН Get start)
                int result = this.fИНН;
                // *** Start programmer edit section *** (Организация.ИНН Get end)

                // *** End programmer edit section *** (Организация.ИНН Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организация.ИНН Set start)

                // *** End programmer edit section *** (Организация.ИНН Set start)
                this.fИНН = value;
                // *** Start programmer edit section *** (Организация.ИНН Set end)

                // *** End programmer edit section *** (Организация.ИНН Set end)
            }
        }
        
        /// <summary>
        /// КПП.
        /// </summary>
        // *** Start programmer edit section *** (Организация.КПП CustomAttributes)

        // *** End programmer edit section *** (Организация.КПП CustomAttributes)
        public virtual int КПП
        {
            get
            {
                // *** Start programmer edit section *** (Организация.КПП Get start)

                // *** End programmer edit section *** (Организация.КПП Get start)
                int result = this.fКПП;
                // *** Start programmer edit section *** (Организация.КПП Get end)

                // *** End programmer edit section *** (Организация.КПП Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организация.КПП Set start)

                // *** End programmer edit section *** (Организация.КПП Set start)
                this.fКПП = value;
                // *** Start programmer edit section *** (Организация.КПП Set end)

                // *** End programmer edit section *** (Организация.КПП Set end)
            }
        }
        
        /// <summary>
        /// Наим.
        /// </summary>
        // *** Start programmer edit section *** (Организация.Наим CustomAttributes)

        // *** End programmer edit section *** (Организация.Наим CustomAttributes)
        [StrLen(255)]
        public virtual string Наим
        {
            get
            {
                // *** Start programmer edit section *** (Организация.Наим Get start)

                // *** End programmer edit section *** (Организация.Наим Get start)
                string result = this.fНаим;
                // *** Start programmer edit section *** (Организация.Наим Get end)

                // *** End programmer edit section *** (Организация.Наим Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организация.Наим Set start)

                // *** End programmer edit section *** (Организация.Наим Set start)
                this.fНаим = value;
                // *** Start programmer edit section *** (Организация.Наим Set end)

                // *** End programmer edit section *** (Организация.Наим Set end)
            }
        }
        
        /// <summary>
        /// РасСчет.
        /// </summary>
        // *** Start programmer edit section *** (Организация.РасСчет CustomAttributes)

        // *** End programmer edit section *** (Организация.РасСчет CustomAttributes)
        public virtual int РасСчет
        {
            get
            {
                // *** Start programmer edit section *** (Организация.РасСчет Get start)

                // *** End programmer edit section *** (Организация.РасСчет Get start)
                int result = this.fРасСчет;
                // *** Start programmer edit section *** (Организация.РасСчет Get end)

                // *** End programmer edit section *** (Организация.РасСчет Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организация.РасСчет Set start)

                // *** End programmer edit section *** (Организация.РасСчет Set start)
                this.fРасСчет = value;
                // *** Start programmer edit section *** (Организация.РасСчет Set end)

                // *** End programmer edit section *** (Организация.РасСчет Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОрганизацияE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОрганизацияE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОрганизацияE", typeof(IIS.INV2.Организация));
                }
            }
            
            /// <summary>
            /// "ОрганизацияL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОрганизацияL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОрганизацияL", typeof(IIS.INV2.Организация));
                }
            }
        }
    }
}
