//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.INV2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Портф ЦБ.
    /// </summary>
    // *** Start programmer edit section *** (ПортфЦБ CustomAttributes)

    // *** End programmer edit section *** (ПортфЦБ CustomAttributes)
    [AutoAltered()]
    [Caption("Портф ЦБ")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПортфЦБE", new string[] {
            "Номер as \'Номер\'",
            "Дата as \'Дата\'",
            "Обязаности as \'Обязаности\'",
            "Сумма as \'Сумма\'",
            "ПодписьК as \'Подпись К\'",
            "ПодписьО as \'Подпись О\'",
            "Сотрудн as \'Сотрудн\'",
            "Сотрудн.ФИО as \'ФИО\'",
            "Организация as \'Организация\'",
            "Организация.Наим as \'Наим\'",
            "УпрОБъек as \'Упр о бъек\'",
            "Клиен as \'Клиен\'",
            "Клиен.Наим as \'Наим\'"}, Hidden=new string[] {
            "Сотрудн.ФИО",
            "Организация.Наим",
            "Клиен.Наим"})]
    [MasterViewDefineAttribute("ПортфЦБE", "Сотрудн", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("ПортфЦБE", "Организация", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наим")]
    [MasterViewDefineAttribute("ПортфЦБE", "УпрОБъек", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "")]
    [MasterViewDefineAttribute("ПортфЦБE", "Клиен", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наим")]
    [View("ПортфЦБL", new string[] {
            "Номер as \'Номер\'",
            "Дата as \'Дата\'",
            "Обязаности as \'Обязаности\'",
            "Сумма as \'Сумма\'",
            "ПодписьК as \'Подпись К\'",
            "ПодписьО as \'Подпись О\'",
            "Сотрудн.ФИО as \'ФИО\'",
            "Организация.Наим as \'Наим\'",
            "Клиен.Наим as \'Наим\'"})]
    public class ПортфЦБ : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private System.DateTime fДата;
        
        private string fОбязаности;
        
        private float fСумма;
        
        private bool fПодписьК;
        
        private bool fПодписьО;
        
        private IIS.INV2.Сотрудн fСотрудн;
        
        private IIS.INV2.Организация fОрганизация;
        
        private IIS.INV2.УпрОБъек fУпрОБъек;
        
        private IIS.INV2.Клиен fКлиен;
        
        // *** Start programmer edit section *** (ПортфЦБ CustomMembers)

        // *** End programmer edit section *** (ПортфЦБ CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ПортфЦБ.Дата CustomAttributes)

        // *** End programmer edit section *** (ПортфЦБ.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ПортфЦБ.Дата Get start)

                // *** End programmer edit section *** (ПортфЦБ.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ПортфЦБ.Дата Get end)

                // *** End programmer edit section *** (ПортфЦБ.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПортфЦБ.Дата Set start)

                // *** End programmer edit section *** (ПортфЦБ.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ПортфЦБ.Дата Set end)

                // *** End programmer edit section *** (ПортфЦБ.Дата Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (ПортфЦБ.Номер CustomAttributes)

        // *** End programmer edit section *** (ПортфЦБ.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (ПортфЦБ.Номер Get start)

                // *** End programmer edit section *** (ПортфЦБ.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (ПортфЦБ.Номер Get end)

                // *** End programmer edit section *** (ПортфЦБ.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПортфЦБ.Номер Set start)

                // *** End programmer edit section *** (ПортфЦБ.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (ПортфЦБ.Номер Set end)

                // *** End programmer edit section *** (ПортфЦБ.Номер Set end)
            }
        }
        
        /// <summary>
        /// Обязаности.
        /// </summary>
        // *** Start programmer edit section *** (ПортфЦБ.Обязаности CustomAttributes)

        // *** End programmer edit section *** (ПортфЦБ.Обязаности CustomAttributes)
        [StrLen(255)]
        public virtual string Обязаности
        {
            get
            {
                // *** Start programmer edit section *** (ПортфЦБ.Обязаности Get start)

                // *** End programmer edit section *** (ПортфЦБ.Обязаности Get start)
                string result = this.fОбязаности;
                // *** Start programmer edit section *** (ПортфЦБ.Обязаности Get end)

                // *** End programmer edit section *** (ПортфЦБ.Обязаности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПортфЦБ.Обязаности Set start)

                // *** End programmer edit section *** (ПортфЦБ.Обязаности Set start)
                this.fОбязаности = value;
                // *** Start programmer edit section *** (ПортфЦБ.Обязаности Set end)

                // *** End programmer edit section *** (ПортфЦБ.Обязаности Set end)
            }
        }
        
        /// <summary>
        /// ПодписьК.
        /// </summary>
        // *** Start programmer edit section *** (ПортфЦБ.ПодписьК CustomAttributes)

        // *** End programmer edit section *** (ПортфЦБ.ПодписьК CustomAttributes)
        public virtual bool ПодписьК
        {
            get
            {
                // *** Start programmer edit section *** (ПортфЦБ.ПодписьК Get start)

                // *** End programmer edit section *** (ПортфЦБ.ПодписьК Get start)
                bool result = this.fПодписьК;
                // *** Start programmer edit section *** (ПортфЦБ.ПодписьК Get end)

                // *** End programmer edit section *** (ПортфЦБ.ПодписьК Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПортфЦБ.ПодписьК Set start)

                // *** End programmer edit section *** (ПортфЦБ.ПодписьК Set start)
                this.fПодписьК = value;
                // *** Start programmer edit section *** (ПортфЦБ.ПодписьК Set end)

                // *** End programmer edit section *** (ПортфЦБ.ПодписьК Set end)
            }
        }
        
        /// <summary>
        /// ПодписьО.
        /// </summary>
        // *** Start programmer edit section *** (ПортфЦБ.ПодписьО CustomAttributes)

        // *** End programmer edit section *** (ПортфЦБ.ПодписьО CustomAttributes)
        public virtual bool ПодписьО
        {
            get
            {
                // *** Start programmer edit section *** (ПортфЦБ.ПодписьО Get start)

                // *** End programmer edit section *** (ПортфЦБ.ПодписьО Get start)
                bool result = this.fПодписьО;
                // *** Start programmer edit section *** (ПортфЦБ.ПодписьО Get end)

                // *** End programmer edit section *** (ПортфЦБ.ПодписьО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПортфЦБ.ПодписьО Set start)

                // *** End programmer edit section *** (ПортфЦБ.ПодписьО Set start)
                this.fПодписьО = value;
                // *** Start programmer edit section *** (ПортфЦБ.ПодписьО Set end)

                // *** End programmer edit section *** (ПортфЦБ.ПодписьО Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (ПортфЦБ.Сумма CustomAttributes)

        // *** End programmer edit section *** (ПортфЦБ.Сумма CustomAttributes)
        public virtual float Сумма
        {
            get
            {
                // *** Start programmer edit section *** (ПортфЦБ.Сумма Get start)

                // *** End programmer edit section *** (ПортфЦБ.Сумма Get start)
                float result = this.fСумма;
                // *** Start programmer edit section *** (ПортфЦБ.Сумма Get end)

                // *** End programmer edit section *** (ПортфЦБ.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПортфЦБ.Сумма Set start)

                // *** End programmer edit section *** (ПортфЦБ.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (ПортфЦБ.Сумма Set end)

                // *** End programmer edit section *** (ПортфЦБ.Сумма Set end)
            }
        }
        
        /// <summary>
        /// Портф ЦБ.
        /// </summary>
        // *** Start programmer edit section *** (ПортфЦБ.Клиен CustomAttributes)

        // *** End programmer edit section *** (ПортфЦБ.Клиен CustomAttributes)
        [PropertyStorage(new string[] {
                "Клиен"})]
        [NotNull()]
        public virtual IIS.INV2.Клиен Клиен
        {
            get
            {
                // *** Start programmer edit section *** (ПортфЦБ.Клиен Get start)

                // *** End programmer edit section *** (ПортфЦБ.Клиен Get start)
                IIS.INV2.Клиен result = this.fКлиен;
                // *** Start programmer edit section *** (ПортфЦБ.Клиен Get end)

                // *** End programmer edit section *** (ПортфЦБ.Клиен Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПортфЦБ.Клиен Set start)

                // *** End programmer edit section *** (ПортфЦБ.Клиен Set start)
                this.fКлиен = value;
                // *** Start programmer edit section *** (ПортфЦБ.Клиен Set end)

                // *** End programmer edit section *** (ПортфЦБ.Клиен Set end)
            }
        }
        
        /// <summary>
        /// Портф ЦБ.
        /// </summary>
        // *** Start programmer edit section *** (ПортфЦБ.Организация CustomAttributes)

        // *** End programmer edit section *** (ПортфЦБ.Организация CustomAttributes)
        [PropertyStorage(new string[] {
                "Организация"})]
        [NotNull()]
        public virtual IIS.INV2.Организация Организация
        {
            get
            {
                // *** Start programmer edit section *** (ПортфЦБ.Организация Get start)

                // *** End programmer edit section *** (ПортфЦБ.Организация Get start)
                IIS.INV2.Организация result = this.fОрганизация;
                // *** Start programmer edit section *** (ПортфЦБ.Организация Get end)

                // *** End programmer edit section *** (ПортфЦБ.Организация Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПортфЦБ.Организация Set start)

                // *** End programmer edit section *** (ПортфЦБ.Организация Set start)
                this.fОрганизация = value;
                // *** Start programmer edit section *** (ПортфЦБ.Организация Set end)

                // *** End programmer edit section *** (ПортфЦБ.Организация Set end)
            }
        }
        
        /// <summary>
        /// Портф ЦБ.
        /// </summary>
        // *** Start programmer edit section *** (ПортфЦБ.Сотрудн CustomAttributes)

        // *** End programmer edit section *** (ПортфЦБ.Сотрудн CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудн"})]
        [NotNull()]
        public virtual IIS.INV2.Сотрудн Сотрудн
        {
            get
            {
                // *** Start programmer edit section *** (ПортфЦБ.Сотрудн Get start)

                // *** End programmer edit section *** (ПортфЦБ.Сотрудн Get start)
                IIS.INV2.Сотрудн result = this.fСотрудн;
                // *** Start programmer edit section *** (ПортфЦБ.Сотрудн Get end)

                // *** End programmer edit section *** (ПортфЦБ.Сотрудн Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПортфЦБ.Сотрудн Set start)

                // *** End programmer edit section *** (ПортфЦБ.Сотрудн Set start)
                this.fСотрудн = value;
                // *** Start programmer edit section *** (ПортфЦБ.Сотрудн Set end)

                // *** End programmer edit section *** (ПортфЦБ.Сотрудн Set end)
            }
        }
        
        /// <summary>
        /// Портф ЦБ.
        /// </summary>
        // *** Start programmer edit section *** (ПортфЦБ.УпрОБъек CustomAttributes)

        // *** End programmer edit section *** (ПортфЦБ.УпрОБъек CustomAttributes)
        [PropertyStorage(new string[] {
                "УпрОБъек"})]
        [NotNull()]
        public virtual IIS.INV2.УпрОБъек УпрОБъек
        {
            get
            {
                // *** Start programmer edit section *** (ПортфЦБ.УпрОБъек Get start)

                // *** End programmer edit section *** (ПортфЦБ.УпрОБъек Get start)
                IIS.INV2.УпрОБъек result = this.fУпрОБъек;
                // *** Start programmer edit section *** (ПортфЦБ.УпрОБъек Get end)

                // *** End programmer edit section *** (ПортфЦБ.УпрОБъек Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПортфЦБ.УпрОБъек Set start)

                // *** End programmer edit section *** (ПортфЦБ.УпрОБъек Set start)
                this.fУпрОБъек = value;
                // *** Start programmer edit section *** (ПортфЦБ.УпрОБъек Set end)

                // *** End programmer edit section *** (ПортфЦБ.УпрОБъек Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПортфЦБE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПортфЦБE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПортфЦБE", typeof(IIS.INV2.ПортфЦБ));
                }
            }
            
            /// <summary>
            /// "ПортфЦБL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПортфЦБL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПортфЦБL", typeof(IIS.INV2.ПортфЦБ));
                }
            }
        }
    }
}
