//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.INV2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сотрудн.
    /// </summary>
    // *** Start programmer edit section *** (Сотрудн CustomAttributes)

    // *** End programmer edit section *** (Сотрудн CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СотруднE", new string[] {
            "ФИО as \'ФИО\'",
            "Должност as \'Должност\'",
            "Должност.Должность as \'Должность\'"}, Hidden=new string[] {
            "Должност.Должность"})]
    [MasterViewDefineAttribute("СотруднE", "Должност", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Должность")]
    [View("СотруднL", new string[] {
            "ФИО as \'ФИО\'",
            "Должност.Должность as \'Должность\'"})]
    public class Сотрудн : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИО;
        
        private IIS.INV2.Должност fДолжност;
        
        // *** Start programmer edit section *** (Сотрудн CustomMembers)

        // *** End programmer edit section *** (Сотрудн CustomMembers)

        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудн.ФИО CustomAttributes)

        // *** End programmer edit section *** (Сотрудн.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудн.ФИО Get start)

                // *** End programmer edit section *** (Сотрудн.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Сотрудн.ФИО Get end)

                // *** End programmer edit section *** (Сотрудн.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудн.ФИО Set start)

                // *** End programmer edit section *** (Сотрудн.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Сотрудн.ФИО Set end)

                // *** End programmer edit section *** (Сотрудн.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Сотрудн.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудн.Должност CustomAttributes)

        // *** End programmer edit section *** (Сотрудн.Должност CustomAttributes)
        [PropertyStorage(new string[] {
                "Должност"})]
        [NotNull()]
        public virtual IIS.INV2.Должност Должност
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудн.Должност Get start)

                // *** End programmer edit section *** (Сотрудн.Должност Get start)
                IIS.INV2.Должност result = this.fДолжност;
                // *** Start programmer edit section *** (Сотрудн.Должност Get end)

                // *** End programmer edit section *** (Сотрудн.Должност Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудн.Должност Set start)

                // *** End programmer edit section *** (Сотрудн.Должност Set start)
                this.fДолжност = value;
                // *** Start programmer edit section *** (Сотрудн.Должност Set end)

                // *** End programmer edit section *** (Сотрудн.Должност Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СотруднE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотруднE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотруднE", typeof(IIS.INV2.Сотрудн));
                }
            }
            
            /// <summary>
            /// "СотруднL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотруднL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотруднL", typeof(IIS.INV2.Сотрудн));
                }
            }
        }
    }
}
