//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.INV2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тип акц.
    /// </summary>
    // *** Start programmer edit section *** (ТипАкц CustomAttributes)

    // *** End programmer edit section *** (ТипАкц CustomAttributes)
    [AutoAltered()]
    [Caption("Тип акц")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТипАкцE", new string[] {
            "ТипАкции as \'Тип акции\'"})]
    [View("ТипАкцL", new string[] {
            "ТипАкции as \'Тип акции\'"})]
    public class ТипАкц : ICSSoft.STORMNET.DataObject
    {
        
        private string fТипАкции;
        
        // *** Start programmer edit section *** (ТипАкц CustomMembers)

        // *** End programmer edit section *** (ТипАкц CustomMembers)

        
        /// <summary>
        /// ТипАкции.
        /// </summary>
        // *** Start programmer edit section *** (ТипАкц.ТипАкции CustomAttributes)

        // *** End programmer edit section *** (ТипАкц.ТипАкции CustomAttributes)
        [StrLen(255)]
        public virtual string ТипАкции
        {
            get
            {
                // *** Start programmer edit section *** (ТипАкц.ТипАкции Get start)

                // *** End programmer edit section *** (ТипАкц.ТипАкции Get start)
                string result = this.fТипАкции;
                // *** Start programmer edit section *** (ТипАкц.ТипАкции Get end)

                // *** End programmer edit section *** (ТипАкц.ТипАкции Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТипАкц.ТипАкции Set start)

                // *** End programmer edit section *** (ТипАкц.ТипАкции Set start)
                this.fТипАкции = value;
                // *** Start programmer edit section *** (ТипАкц.ТипАкции Set end)

                // *** End programmer edit section *** (ТипАкц.ТипАкции Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТипАкцE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТипАкцE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТипАкцE", typeof(IIS.INV2.ТипАкц));
                }
            }
            
            /// <summary>
            /// "ТипАкцL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТипАкцL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТипАкцL", typeof(IIS.INV2.ТипАкц));
                }
            }
        }
    }
}
