//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.INV2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тч_реес.
    /// </summary>
    // *** Start programmer edit section *** (Тч_реес CustomAttributes)

    // *** End programmer edit section *** (Тч_реес CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("Тч_реесE", new string[] {
            "Номинал as \'Номинал\'",
            "Сумма as \'Сумма\'",
            "ДоляУК as \'Доля УК\'",
            "Основание as \'Основание\'",
            "ТипАкц as \'Тип акц\'",
            "ТипАкц.ТипАкции as \'Тип акции\'"}, Hidden=new string[] {
            "ТипАкц.ТипАкции"})]
    [MasterViewDefineAttribute("Тч_реесE", "ТипАкц", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ТипАкции")]
    [View("Тч_реесL", new string[] {
            "Номинал as \'Номинал\'",
            "Сумма as \'Сумма\'",
            "ДоляУК as \'Доля УК\'",
            "Основание as \'Основание\'",
            "ТипАкц.ТипАкции as \'Тип акции\'"})]
    public class Тч_реес : ICSSoft.STORMNET.DataObject
    {
        
        private float fНоминал;
        
        private float fСумма;
        
        private float fДоляУК;
        
        private string fОснование;
        
        private IIS.INV2.ТипАкц fТипАкц;
        
        // *** Start programmer edit section *** (Тч_реес CustomMembers)

        // *** End programmer edit section *** (Тч_реес CustomMembers)

        
        /// <summary>
        /// ДоляУК.
        /// </summary>
        // *** Start programmer edit section *** (Тч_реес.ДоляУК CustomAttributes)

        // *** End programmer edit section *** (Тч_реес.ДоляУК CustomAttributes)
        public virtual float ДоляУК
        {
            get
            {
                // *** Start programmer edit section *** (Тч_реес.ДоляУК Get start)

                // *** End programmer edit section *** (Тч_реес.ДоляУК Get start)
                float result = this.fДоляУК;
                // *** Start programmer edit section *** (Тч_реес.ДоляУК Get end)

                // *** End programmer edit section *** (Тч_реес.ДоляУК Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Тч_реес.ДоляУК Set start)

                // *** End programmer edit section *** (Тч_реес.ДоляУК Set start)
                this.fДоляУК = value;
                // *** Start programmer edit section *** (Тч_реес.ДоляУК Set end)

                // *** End programmer edit section *** (Тч_реес.ДоляУК Set end)
            }
        }
        
        /// <summary>
        /// Номинал.
        /// </summary>
        // *** Start programmer edit section *** (Тч_реес.Номинал CustomAttributes)

        // *** End programmer edit section *** (Тч_реес.Номинал CustomAttributes)
        public virtual float Номинал
        {
            get
            {
                // *** Start programmer edit section *** (Тч_реес.Номинал Get start)

                // *** End programmer edit section *** (Тч_реес.Номинал Get start)
                float result = this.fНоминал;
                // *** Start programmer edit section *** (Тч_реес.Номинал Get end)

                // *** End programmer edit section *** (Тч_реес.Номинал Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Тч_реес.Номинал Set start)

                // *** End programmer edit section *** (Тч_реес.Номинал Set start)
                this.fНоминал = value;
                // *** Start programmer edit section *** (Тч_реес.Номинал Set end)

                // *** End programmer edit section *** (Тч_реес.Номинал Set end)
            }
        }
        
        /// <summary>
        /// Основание.
        /// </summary>
        // *** Start programmer edit section *** (Тч_реес.Основание CustomAttributes)

        // *** End programmer edit section *** (Тч_реес.Основание CustomAttributes)
        [StrLen(255)]
        public virtual string Основание
        {
            get
            {
                // *** Start programmer edit section *** (Тч_реес.Основание Get start)

                // *** End programmer edit section *** (Тч_реес.Основание Get start)
                string result = this.fОснование;
                // *** Start programmer edit section *** (Тч_реес.Основание Get end)

                // *** End programmer edit section *** (Тч_реес.Основание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Тч_реес.Основание Set start)

                // *** End programmer edit section *** (Тч_реес.Основание Set start)
                this.fОснование = value;
                // *** Start programmer edit section *** (Тч_реес.Основание Set end)

                // *** End programmer edit section *** (Тч_реес.Основание Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (Тч_реес.Сумма CustomAttributes)

        // *** End programmer edit section *** (Тч_реес.Сумма CustomAttributes)
        public virtual float Сумма
        {
            get
            {
                // *** Start programmer edit section *** (Тч_реес.Сумма Get start)

                // *** End programmer edit section *** (Тч_реес.Сумма Get start)
                float result = this.fСумма;
                // *** Start programmer edit section *** (Тч_реес.Сумма Get end)

                // *** End programmer edit section *** (Тч_реес.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Тч_реес.Сумма Set start)

                // *** End programmer edit section *** (Тч_реес.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (Тч_реес.Сумма Set end)

                // *** End programmer edit section *** (Тч_реес.Сумма Set end)
            }
        }
        
        /// <summary>
        /// Тч_реес.
        /// </summary>
        // *** Start programmer edit section *** (Тч_реес.ТипАкц CustomAttributes)

        // *** End programmer edit section *** (Тч_реес.ТипАкц CustomAttributes)
        [PropertyStorage(new string[] {
                "ТипАкц"})]
        [NotNull()]
        public virtual IIS.INV2.ТипАкц ТипАкц
        {
            get
            {
                // *** Start programmer edit section *** (Тч_реес.ТипАкц Get start)

                // *** End programmer edit section *** (Тч_реес.ТипАкц Get start)
                IIS.INV2.ТипАкц result = this.fТипАкц;
                // *** Start programmer edit section *** (Тч_реес.ТипАкц Get end)

                // *** End programmer edit section *** (Тч_реес.ТипАкц Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Тч_реес.ТипАкц Set start)

                // *** End programmer edit section *** (Тч_реес.ТипАкц Set start)
                this.fТипАкц = value;
                // *** Start programmer edit section *** (Тч_реес.ТипАкц Set end)

                // *** End programmer edit section *** (Тч_реес.ТипАкц Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "Тч_реесE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Тч_реесE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Тч_реесE", typeof(IIS.INV2.Тч_реес));
                }
            }
            
            /// <summary>
            /// "Тч_реесL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Тч_реесL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Тч_реесL", typeof(IIS.INV2.Тч_реес));
                }
            }
        }
    }
}
