//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.INV2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Т ч_выпл.
    /// </summary>
    // *** Start programmer edit section *** (ТЧ_выпл CustomAttributes)

    // *** End programmer edit section *** (ТЧ_выпл CustomAttributes)
    [AutoAltered()]
    [Caption("Т ч_выпл")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧ_выплE", new string[] {
            "Сумма as \'Сумма\'"})]
    [View("ТЧ_выплL", new string[] {
            "Сумма as \'Сумма\'"})]
    public class ТЧ_выпл : ICSSoft.STORMNET.DataObject
    {
        
        private float fСумма;
        
        // *** Start programmer edit section *** (ТЧ_выпл CustomMembers)

        // *** End programmer edit section *** (ТЧ_выпл CustomMembers)

        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (ТЧ_выпл.Сумма CustomAttributes)

        // *** End programmer edit section *** (ТЧ_выпл.Сумма CustomAttributes)
        public virtual float Сумма
        {
            get
            {
                // *** Start programmer edit section *** (ТЧ_выпл.Сумма Get start)

                // *** End programmer edit section *** (ТЧ_выпл.Сумма Get start)
                float result = this.fСумма;
                // *** Start programmer edit section *** (ТЧ_выпл.Сумма Get end)

                // *** End programmer edit section *** (ТЧ_выпл.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧ_выпл.Сумма Set start)

                // *** End programmer edit section *** (ТЧ_выпл.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (ТЧ_выпл.Сумма Set end)

                // *** End programmer edit section *** (ТЧ_выпл.Сумма Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧ_выплE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧ_выплE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧ_выплE", typeof(IIS.INV2.ТЧ_выпл));
                }
            }
            
            /// <summary>
            /// "ТЧ_выплL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧ_выплL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧ_выплL", typeof(IIS.INV2.ТЧ_выпл));
                }
            }
        }
    }
}
