//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.INV2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тч_ портф.
    /// </summary>
    // *** Start programmer edit section *** (Тч_Портф CustomAttributes)

    // *** End programmer edit section *** (Тч_Портф CustomAttributes)
    [AutoAltered()]
    [Caption("Тч_ портф")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("Тч_ПортфE", new string[] {
            "Номинал as \'Номинал\'",
            "Колич as \'Колич\'",
            "Сумма as \'Сумма\'",
            "ТипАкц as \'Тип акц\'",
            "ТипАкц.ТипАкции as \'Тип акции\'"}, Hidden=new string[] {
            "ТипАкц.ТипАкции"})]
    [MasterViewDefineAttribute("Тч_ПортфE", "ТипАкц", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ТипАкции")]
    [View("Тч_ПортфL", new string[] {
            "Номинал as \'Номинал\'",
            "Колич as \'Колич\'",
            "Сумма as \'Сумма\'",
            "ТипАкц.ТипАкции as \'Тип акции\'"})]
    public class Тч_Портф : ICSSoft.STORMNET.DataObject
    {
        
        private float fНоминал;
        
        private int fКолич;
        
        private float fСумма;
        
        private IIS.INV2.ТипАкц fТипАкц;
        
        // *** Start programmer edit section *** (Тч_Портф CustomMembers)

        // *** End programmer edit section *** (Тч_Портф CustomMembers)

        
        /// <summary>
        /// Колич.
        /// </summary>
        // *** Start programmer edit section *** (Тч_Портф.Колич CustomAttributes)

        // *** End programmer edit section *** (Тч_Портф.Колич CustomAttributes)
        public virtual int Колич
        {
            get
            {
                // *** Start programmer edit section *** (Тч_Портф.Колич Get start)

                // *** End programmer edit section *** (Тч_Портф.Колич Get start)
                int result = this.fКолич;
                // *** Start programmer edit section *** (Тч_Портф.Колич Get end)

                // *** End programmer edit section *** (Тч_Портф.Колич Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Тч_Портф.Колич Set start)

                // *** End programmer edit section *** (Тч_Портф.Колич Set start)
                this.fКолич = value;
                // *** Start programmer edit section *** (Тч_Портф.Колич Set end)

                // *** End programmer edit section *** (Тч_Портф.Колич Set end)
            }
        }
        
        /// <summary>
        /// Номинал.
        /// </summary>
        // *** Start programmer edit section *** (Тч_Портф.Номинал CustomAttributes)

        // *** End programmer edit section *** (Тч_Портф.Номинал CustomAttributes)
        public virtual float Номинал
        {
            get
            {
                // *** Start programmer edit section *** (Тч_Портф.Номинал Get start)

                // *** End programmer edit section *** (Тч_Портф.Номинал Get start)
                float result = this.fНоминал;
                // *** Start programmer edit section *** (Тч_Портф.Номинал Get end)

                // *** End programmer edit section *** (Тч_Портф.Номинал Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Тч_Портф.Номинал Set start)

                // *** End programmer edit section *** (Тч_Портф.Номинал Set start)
                this.fНоминал = value;
                // *** Start programmer edit section *** (Тч_Портф.Номинал Set end)

                // *** End programmer edit section *** (Тч_Портф.Номинал Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (Тч_Портф.Сумма CustomAttributes)

        // *** End programmer edit section *** (Тч_Портф.Сумма CustomAttributes)
        public virtual float Сумма
        {
            get
            {
                // *** Start programmer edit section *** (Тч_Портф.Сумма Get start)

                // *** End programmer edit section *** (Тч_Портф.Сумма Get start)
                float result = this.fСумма;
                // *** Start programmer edit section *** (Тч_Портф.Сумма Get end)

                // *** End programmer edit section *** (Тч_Портф.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Тч_Портф.Сумма Set start)

                // *** End programmer edit section *** (Тч_Портф.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (Тч_Портф.Сумма Set end)

                // *** End programmer edit section *** (Тч_Портф.Сумма Set end)
            }
        }
        
        /// <summary>
        /// Тч_ портф.
        /// </summary>
        // *** Start programmer edit section *** (Тч_Портф.ТипАкц CustomAttributes)

        // *** End programmer edit section *** (Тч_Портф.ТипАкц CustomAttributes)
        [PropertyStorage(new string[] {
                "ТипАкц"})]
        [NotNull()]
        public virtual IIS.INV2.ТипАкц ТипАкц
        {
            get
            {
                // *** Start programmer edit section *** (Тч_Портф.ТипАкц Get start)

                // *** End programmer edit section *** (Тч_Портф.ТипАкц Get start)
                IIS.INV2.ТипАкц result = this.fТипАкц;
                // *** Start programmer edit section *** (Тч_Портф.ТипАкц Get end)

                // *** End programmer edit section *** (Тч_Портф.ТипАкц Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Тч_Портф.ТипАкц Set start)

                // *** End programmer edit section *** (Тч_Портф.ТипАкц Set start)
                this.fТипАкц = value;
                // *** Start programmer edit section *** (Тч_Портф.ТипАкц Set end)

                // *** End programmer edit section *** (Тч_Портф.ТипАкц Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "Тч_ПортфE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Тч_ПортфE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Тч_ПортфE", typeof(IIS.INV2.Тч_Портф));
                }
            }
            
            /// <summary>
            /// "Тч_ПортфL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Тч_ПортфL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Тч_ПортфL", typeof(IIS.INV2.Тч_Портф));
                }
            }
        }
    }
}
