//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.INV2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Упр о бъек.
    /// </summary>
    // *** Start programmer edit section *** (УпрОБъек CustomAttributes)

    // *** End programmer edit section *** (УпрОБъек CustomAttributes)
    [AutoAltered()]
    [Caption("Упр о бъек")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("УпрОБъекE", new string[0])]
    [View("УпрОБъекL", new string[0])]
    public class УпрОБъек : ICSSoft.STORMNET.DataObject
    {
        
        // *** Start programmer edit section *** (УпрОБъек CustomMembers)

        // *** End programmer edit section *** (УпрОБъек CustomMembers)

        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "УпрОБъекE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УпрОБъекE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УпрОБъекE", typeof(IIS.INV2.УпрОБъек));
                }
            }
            
            /// <summary>
            /// "УпрОБъекL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УпрОБъекL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УпрОБъекL", typeof(IIS.INV2.УпрОБъек));
                }
            }
        }
    }
}
